Remove warning about unused variable when building on macOS
On macOS, neither of the two cases implemented in set_mouse_accel applies.
We get the following eror message:

  CC       spice-widget.lo
spice-widget.c:944:26: error: unused variable 'd' [-Werror,-Wunused-variable]
    SpiceDisplayPrivate *d = display->priv;